### PR TITLE
Feature/customisable ckeditor

### PR DESCRIPTION
**Pull request by petrklus**
Added ability to include CKEditor settings for the blog abstract and post contents (as per https://github.com/divio/djangocms-text-ckeditor/#customizing-htmlfield-editor). Discussed at https://github.com/nephila/djangocms-blog/issues/446

### CODE REVIEW

**Comment by yakky** [comment]
@petrklus I think it's :+1:, but I'd like to have it  against release/0.9.x branch to release a patch version which includes this. And add an item to the changelog
Thanks for spending some time working on this

**Comment by petrklus** [comment]
Shall I re-do it against https://github.com/nephila/djangocms-blog/tree/release/0.9.x @yakky ?

**Comment by yakky** [comment]
Yes please, so I can include this in next 0.9 release

**Comment by yakky** [comment]
Merged with #449 
It will be forward ported to develop after next 0.9 release

**Pull request closed without merging**
