### PR TITLE
add placeholder fields to appconfig

### PR DESCRIPTION
**Pull request by razisayyed**
Add various placeholder fields to AppConfig

This way we can add plugins/app for list and details pages (same as aldryn-newsblog).

### CODE REVIEW

**Comment by yakky** [comment]
I'm not keen to add this. I think static placeholders are much more flexible in this respect, as you can define the one you really want in the template instead of having the page cluttered with empty placeholders.
Would static placeholder solve your use case?

**Comment by razisayyed** [comment]
I do not know. But if I understand static placeholders the right way, I think they will be shared among different app instances using the same templates set, am I right?

**Comment by yakky** [comment]
Yes, but with templates set support of 0.9 you can have different sets of templates for different applications, or you can just use the namespace in the name of the static placeholders to have different static placeholders  in the same template set

**Comment by razisayyed** [comment]
I like the Idea of using namespace in the name of static placeholders, I will give it a try.

**Comment by razisayyed** [comment]
namespace in the name of static placeholders works fine. I thinknit is better approach than adding placeholder fields to AppConfig. It give users more flexibility.

**Comment by yakky** [comment]
Thanks for reporting and liking the static placeholders solution! :+1:

**Pull request closed without merging**
