### PR TITLE
Add aldryn-apphooks config

### LINKED ISSUE #65: Multiple blog layouts?
Hi,

I'm not a django expert by any means, so forgive me if I'm missing something obvious. I've spent the last few days learning the ropes of django cms and chose your blog to go with it. Is there a way to choose different layouts for posts similar to {% CMS TEMPLATES %} for a CMS page?

Thanks,
Ben

### LINKED ISSUE #77: Creating multiple independent blogs
I wanted to create a site with multiple independent blog pages and I was hoping the "application instance name" field will allow me to do that.

What does the "Application Instance name" field do?

I guessed that it might allow me to create multiple pages, and associate them with different blogs. Basically, create separate independent blog pages (for example, I could have a blog on physics simulations, and another on origami and I want to keep them completely separate).

However, on creating 2 different pages, both associated with the Blog application, but with different "application instance names", I saw that any blog posts that I create in one show up in the other as well.

Is there a way to create multiple independent blogs with djangocms-blog?

ps: This might be a django cms question rather than a djangocms-blog question, and I apologize in advance if that is the case...

(Edited issue title and text)

### LINKED ISSUE #126: Move to aldryn-apphooks-config
Fix #77 
Fix #65

### LINKED ISSUE #146: Permalink type
Hi,

I see that is not possible config the settings to change the permalink type as aldryn-newsblog does (I don't want display the dates). 
Any hints to remove dates from URL?
Is this feature in your near-future plans?
In my opinion haystack + multilingual tags + permalink would be great.

Thanks

### PR DESCRIPTION
**Pull request by yakky**
Fix #126
Fix #77
Fix #65 
Fix #146 

* [x] Multiple apphooks
* [x] Add posts to menu
* [x] Configurable permalinks
* [ ] Add haystack index
* [x] Move configuration to apphook config
* [x] Setting for menu style (None, Categories, Posts, Categories & Posts)
* [x] Autosetup

### CODE REVIEW

**Comment by motleytech** [comment]
:+1: 
Sweet... would love to see this soon on the develop branch.

I would enjoy updating my site to use this feature.

**Comment by motleytech** [comment]
Might be jumping the gun here a little, but I could no wait until this was merged into develop to give it a shot.

I cloned this repo and merged feature/appcnfg to develop branch and created a new django-cms project (following the usual steps from the readme.md at https://github.com/nephila/djangocms-blog).

I successfully created 2 separate blog pages associating each with different app config instances, and created one post on each of them. The separate blogs now showed their own posts. GREAT.

However, when I clicked on the post to view it, it ran into an error...
```
TypeError at /en/blog2/2015/09/27/first-post-second-blog/
get_meta_attribute() takes exactly 2 arguments (1 given)
Request Method:	GET
Request URL:	http://192.168.1.14:8080/en/blog2/2015/09/27/first-post-second-blog/
Django Version:	1.6.11
Exception Type:	TypeError
Exception Value:	
get_meta_attribute() takes exactly 2 arguments (1 given)
Exception Location:	/home/nagarajan/dev/multiblog/venv/local/lib/python2.7/site-packages/django_meta_mixin-0.1.1-py2.7.egg/meta_mixin/models.py in as_meta, line 52
Python Executable:	/home/nagarajan/dev/multiblog/venv/bin/python
Python Version:	2.7.3
```

```
/home/nagarajan/dev/multiblog/venv/local/lib/python2.7/site-packages/djangocms_blog-0.5.1.dev1-py2.7.egg/djangocms_blog/views.py in get_context_data

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['meta'] = self.get_object().as_meta() 
```

```
/home/nagarajan/dev/multiblog/venv/local/lib/python2.7/site-packages/django_meta_mixin-0.1.1-py2.7.egg/meta_mixin/models.py in as_meta

        metadata.update(self._metadata_default)
        meta = Meta()
        for field, value in self._metadata.items():
            if value:
                attr = getattr(self, value, False)
                if attr is not False:
                    if callable(attr):
                        data = attr() 
```


This is my virtualenv configuration...
```
aldryn-apphooks-config==0.2.5
cmsplugin-filer==0.10.2
dj-database-url==0.3.0
Django==1.6.11
django-admin-enhancer==1.0.0
django-appconf==1.0.1
django-appdata==0.1.4
django-classy-tags==0.6.2
django-cms==3.0.15
django-filer==0.9.12
django-meta==0.3.1
django-meta-mixin==0.1.1
django-mptt==0.6.1
django-parler==1.5
django-polymorphic==0.7.1
django-reversion==1.8.5
django-sekizai==0.8.2
Django-Select2==4.3.2
django-taggit==0.17.1
django-taggit-autosuggest==0.2.7
django-taggit-templatetags==0.4.6.dev0
django-templatetag-sugar==1.0
djangocms-admin-style==0.2.8
djangocms-blog==0.5.1.dev1
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.2.0
djangocms-googlemap==0.3
djangocms-inherit==0.1
djangocms-installer==0.8.0
djangocms-link==1.6.2
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.6.0
djangocms-video==0.1
easy-thumbnails==2.2
html5lib==0.9999999
Pillow==2.9.0
pytz==2015.6
six==1.9.0
South==1.0.2
tzlocal==1.2
Unidecode==0.4.18
```

**Comment by yakky** [comment]
Wow, thanks for being so impatient! :)
This branch requires the master branch of django-meta-mixin (that will be released as 0.2). You can just pip install that from github

**Comment by motleytech** [comment]
Thanks @yakky . It seems to work fine now.

I will try to migrate my existing blog to this and will let you know how that goes.

**Comment by yakky** [comment]
@motleytech thanks for your test!
Datamigration should correctly migrate existing installations to the new setup, let me know if it's handled correctly

**Comment by motleytech** [comment]
Tried data migration on my blog database using `python manage.py syncdb` followed by `python manage.py migrate`. It ran into the following error...

```
Running migrations for djangocms_blog:
 - Migrating forwards to 0015_create_appconfig.
 > djangocms_blog:0011_chg_field_post_translation_abstract
 > djangocms_blog:0012_move_tags
 > djangocms_blog:0013_auto
 > djangocms_blog:0014_auto__add_blogconfigtranslation__add_unique_blogconfigtranslation_lang
 > djangocms_blog:0015_create_appconfig
Error in migration: djangocms_blog:0015_create_appconfig
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/djangocms_blog-0.5.1.dev1-py2.7.egg/djangocms_blog/south_migrations/0015_create_appconfig.py", line 21, in forwards
    config = BlogConfig.objects.create(namespace=page.application_namespace)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "set_author" of relation "djangocms_blog_blogconfig" does not exist
LINE 1: INSERT INTO "djangocms_blog_blogconfig" ("set_author", "name...
```

**Comment by yakky** [comment]
@motleytech argh, sorry, apparently a south migration was missing. It should be fixed now

**Comment by motleytech** [comment]
@yakky 
Thanks man. Ran into another error...

```
Running migrations for djangocms_blog:
 - Migrating forwards to 0016_create_appconfig.
 > djangocms_blog:0011_chg_field_post_translation_abstract
 > djangocms_blog:0012_move_tags
 > djangocms_blog:0013_auto
 > djangocms_blog:0014_auto__add_blogconfigtranslation__add_unique_blogconfigtranslation_lang
 > djangocms_blog:0015_auto__del_field_blogconfig_paginate_by__del_field_blogconfig_set_autho
FATAL ERROR - The following SQL query failed: ALTER TABLE "djangocms_blog_blogconfig" DROP COLUMN "paginate_by" CASCADE;
The error was: column "paginate_by" of relation "djangocms_blog_blogconfig" does not exist

Error in migration: djangocms_blog:0015_auto__del_field_blogconfig_paginate_by__del_field_blogconfig_set_autho
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()

<snip>

  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "paginate_by" of relation "djangocms_blog_blogconfig" does not exist

```

**Comment by yakky** [comment]
Ok, I had the chance to test in a live non trivial project. This time shoud be fixed. Sorry @motleytech and thanks for your patience

**Comment by motleytech** [comment]
@yakky 
No need for apologies. I am glad to be part of this, and happy to help in whatever way possible.

I tried the latest migrations and it seemed to work this time. Then I started to create a separate blog page and ran into some problems.

Here is what I did...

Created a new cms page - with title `newpage`, and filled in other required fileds. Then, Save and publish the page

New menu item showed up for 'newpage'. Clicking on it gave this error... (this page is not associated with the blog application, so not sure why aldryn_apphooks_config is involved here).

```
ImproperlyConfigured at /en/newpage/
No registered apphook None found
Request Method:	GET
Request URL:	http://192.168.1.14:8001/en/newpage/
Django Version:	1.6.10
Exception Type:	ImproperlyConfigured
Exception Value:
No registered apphook None found
Exception Location:	/home/username/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/cms/apphook_pool.py in get_apphook, line 97
Python Executable:	/home/username/dev/ws_project/venvs/cms_venv/bin/python
Python Version:	2.7.3
Python Path:
['/home/username/dev/ws_project/webcms/djcms',
 '/home/username/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/aldryn_apphooks_config-0.2.5-py2.7.egg',
 '/home/username/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/django_appdata-0.1.4-py2.7.egg',
 '/home/username/dev/ws_project/venvs/cms_venv/src/django-meta-mixin-master',
 '/home/username/dev/ws_project/venvs/cms_venv/lib/python2.7',
 '/home/username/dev/ws_project/venvs/cms_venv/lib/python2.7/plat-linux2',
 '/home/username/dev/ws_project/venvs/cms_venv/lib/python2.7/lib-tk',
 '/home/username/dev/ws_project/venvs/cms_venv/lib/python2.7/lib-old',
 '/home/username/dev/ws_project/venvs/cms_venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/username/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages',
 '/home/username/dev/ws_project/webcms/djcms/djangocms-blog']
Server time:	Wed, 30 Sep 2015 20:18:50 -0700

Error is at the following location...

/home/username/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/aldryn_apphooks_config-0.2.5-py2.7.egg/aldryn_apphooks_config/utils.py in get_app_instance
    Returns a tuple containing the current namespace and the AppHookConfig instance
    :param request: request object
    :return: namespace, config
    """
    app = None
    if getattr(request, 'current_page', None):
        app = apphook_pool.get_apphook(request.current_page.application_urls) 
```

Restarting the server process does not help.

On editing the new page's advanced settings, I ran into another issue...

When I associated the page with the Blog application and attempted to assign a new Application configuration, I got an error at the top saying `Please correct the error below`. However, there is no field in red below.

I inspected the page source and saw that there is a hidden field with the label `Application instance name:` which has the associated error `A instance with this name already exists`. I made the field visible, which now showed up along with the error message in red, and had the text `djangocms_blog` in the text field. I changed this to `djangocms_blog2`, just to give it a new name and clicked on save.

The save worked, but I knew this was a terrible hack and had very little chance of working. As expected, it didn't really work.

On clicking on the newly created page, I got this error

```
Page not found (404)
Request Method:	GET
Request URL:	http://192.168.1.14:8001/en/newpage/

No blog article found matching the query, tried languages: en

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

**Comment by yakky** [comment]
@motleytech hmm, that's weird, which django CMS version are you using?

**Comment by motleytech** [comment]
I am on `django-cms==3.0.15`. I see that there is a 3.0.16 available... could that be the culprit?

**Comment by yakky** [comment]
@motleytech it should not. I'll give it a run on 3.0.15

**Comment by motleytech** [comment]
@yakky Thanks
Let me know if you run into issues. In the meanwhile, I will upgrade to 3.0.16 and see if that makes a difference.

**Comment by motleytech** [comment]
Sorry... wrong info. I am on `3.0.12`. I looked up the `3.0.15` in the wrong place.

**Comment by yakky** [comment]
I cannot reproduce the behavior on 3.0.15 or 3.0.12 
Error 1) can be easily fixed on apphooks config by playing defensive, but I cannot see why it could happen
Regarding the error 2), does your advanced settings looks like this?
blog

**Comment by motleytech** [comment]
@yakky 
Yes, it looks exactly like that.

**Comment by motleytech** [comment]
I upgraded to 3.0.15 and I am able to replicate the same problems I had with 3.0.12.

I have 2 pages in my site... one is associated with the Blog application. The other is a simple cms page - the about page.

After the migration, I am able to see the blog and all the blog posts.
However, I am unable to view the cms about page, and getting this error when I click on the about menu item...

```
ImproperlyConfigured at /en/about/
No registered apphook u'' found
Request Method:	GET
Request URL:	http://192.168.1.14:8001/en/about/
Django Version:	1.6.10
Exception Type:	ImproperlyConfigured
Exception Value:	
No registered apphook u'' found
Exception Location:	/home/nagarajan/dev/ws_project/venvs/cms_venv/local/lib/python2.7/site-packages/cms/apphook_pool.py in get_apphook, line 97
```

pic1

Also, the about page shows up as unpublished in the left admin panel, and when I try to publish it, I see the following error in the terminal...

```
[30/Sep/2015 22:54:17] "GET /en/admin/cms/page/3/en/publish/?redirect_language=en&redirect_page_id= HTTP/1.1" 405 0
```

**Comment by yakky** [comment]
Ah! I think you just found a bug in django CMS / apphook config :)

**Comment by motleytech** [comment]
Damn bugs. :rage: Grrrr....

I am gonna see if I can find the bug and report it to the django cms team.

**Comment by yakky** [comment]
No worries, I'm investigating. I just fixed 1) in https://github.com/aldryn/aldryn-apphooks-config/tree/feature/code_style
With the current implementation of the configurable slugs, however, you can't have a subpage in the blog. But I think I can fix that
What really baffles me is the error 2)

**Comment by yakky** [comment]
You can support subpages of the blog page by setting:

    BLOG_PERMALINKS_URLS = {
        'full_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$',
        'short_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>\w[-\w]*)/$',
        'category': r'^post/(?P<category>\w[-\w]*)/(?P<slug>\w[-\w]*)/$',
        'slug': r'^post/(?P<slug>\w[-\w]*)/$',
    }

So that 'category' and 'slug' kind of slug does not conflict with django CMS ones

**Comment by motleytech** [comment]
I am hoping that fixing 1 will have some effect on 2. In the meanwhile, let me try your suggestion about the blog permalinks thing.

**Comment by motleytech** [comment]
@yakky 
Also, any idea why the problem with the django cms apphook config shows up now, after the migration (and not before)?

**Comment by yakky** [comment]
@motleytech before the migration apphook config was not available for the blog as the blog app did not declare support for it, so the CMS fallbacked to the "old" behavior

**Comment by motleytech** [comment]
Got it... I was suspecting something on those lines.

**Comment by motleytech** [comment]
@yakky 
Applied your `play safe` fix from `aldryn_apphooks_config`. That got rid of the improperly configured error on accessing the about page... but ran into another error.

```
Page not found (404)
Request Method:	GET
Request URL:	http://192.168.1.14:8001/en/about/
No blog article found matching the query, tried languages: en
```

I wonder why its searching for a `blog article` in the last line... the about page is not linked with the blog. Its just a cms page. :confused:

**Comment by yakky** [comment]
That's related to the permalink thing

**Comment by motleytech** [comment]
Thanks... Now I understand what was wrong with the about page link. Had to fix a typo to get that to work properly.

BLOG_PERMALINK**S**_URLS should be BLOG_PERMALINK_URLS

**Comment by yakky** [comment]
@motleytech oops, sorry!

**Comment by motleytech** [comment]
Yayy... it works now!!! Sweeet!

I am able to have separate blog pages with their own posts, along with cms pages.

Everything seems to work fine now. Thanks a ton for sticking with this @yakky

**Comment by yakky** [comment]
@motleytech good! Thanks a ton for testing this and helping fixing a few things along the way

**Comment by vnavascues** [comment]
Hi guys,
I've following your steps and that app awesome :).
I've noticed than when you **Add blog article** the **Category** box is empty despite the fact there exist some categories. But if you **Save and continue editing** suddenly categories appear.

**Comment by yakky** [comment]
@vnavascues indeed, thanks for spotting this

**Comment by motleytech** [comment]
@yakky 
I see that after migrating my blog, the menu shows the categories of a blog as submenu items of the blog.

Is this a bug or by design?

**Comment by yakky** [comment]
It's a new feature since 0.5.0. Actually we can now add a setting for this in the apphook config

**Comment by motleytech** [comment]
Sorry... I am a little rusty in my django. How can I add this setting?

Also, we should have aldryn_apphooks_config in the settings INSTALLED_APPS in order for the collectstatic to copy the js and css from the app to the static location.

One more problem which I ran into again recently (because I had not created a new blog page in a few days). Whenever I try creating a new page associated with the blog application (in the advanced settings), the `Application Instance name` field is always hidden and defaults to "djangocms_blog". This gives an error (which I reported up in this discussion) without being able to highlight the error field.

Currently I am working around this by going into dev tools, unhiding the filed and giving the app instance a new name.

Any idea what could be wrong here? This looks like a cms bug.

**Comment by motleytech** [comment]
The error due to `Application Instance name` went away after I installed apphooks config in the right place. Kindly ignore my comments on that error.

**Comment by yakky** [comment]
@motleytech I'll push the new setting shortly and the README fix

**Comment by yakky** [comment]
@motleytech Menu configuration landed

**Comment by motleytech** [comment]
Thanks @yakky 
Will start playing around with it right away.

**Comment by yakky** [comment]
@motleytech @vnavascues I'm about to merge this into develop and release an alpha version to make testing easier. Search index will land later

**Comment by motleytech** [comment]
Thanks again for this excellent set of features.

**Comment by yakky** [comment]
@motleytech thanks for your valuable tests

**Pull request merged**
