### PR TITLE
add info about urls.py

### PR DESCRIPTION
**Pull request by jedie**
see: https://github.com/nephila/djangocms-blog/issues/75

### CODE REVIEW

**Comment by yakky** [comment]
Blog it's supposed to be added by using apphooks. That's the documented and proper way to add it to a django CMS page.

**Comment by jedie** [comment]
Ah! you are right. This is not needed.

Sorry for confusion...

**Comment by findinshop** [comment]
Sorry! I speak English very bad.

 i installed you djangocms_blog and insert in urls.py line

from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^blog/', include('djangocms_blog.urls', namespace='djangocms_blog')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA



as a result of getting an error

http://127.0.0.1:8000/ru/blog/2015/09/20/test/

Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/ru/blog/2015/09/20/test/
Using the URLconf defined in www.urls, Django tried these URL patterns, in this order:
^media/(?P<path>.*)$
^static\/(?P<path>.*)$
^ru/ ^admin/
^ru/ ^sitemap\.xml$
^ru/ ^select2/
^ru/ ^ ^(?P<slug>[0-9A-Za-z-_.//]+)/$ [name='pages-details-by-slug']
^ru/ ^ ^$ [name='pages-root']
^ru/ ^taggit_autosuggest/
^ru/ ^blog/ ^$ [name='posts-latest']
^ru/ ^blog/ ^feed/$ [name='posts-latest-feed']
^ru/ ^blog/ ^(?P<year>\d{4})/$ [name='posts-archive']
^ru/ ^blog/ ^(?P<year>\d{4})/(?P<month>\d{1,2})/$ [name='posts-archive']
^ru/ ^blog/ ^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$ [name='post-detail']
^ru/ ^blog/ ^author/(?P<username>[\w\.@+-]+)/$ [name='posts-author']
^ru/ ^blog/ ^category/(?P<category>[\w\.@+-]+)/$ [name='posts-category']
^ru/ ^blog/ ^tag/(?P<tag>[-\w]+)/$ [name='posts-tagged']
^ru/ ^blog/ ^tag/(?P<tag>[-\w]+)/feed/$ [name='posts-tagged-feed']
The current URL, /ru/blog/2015/09/20/test/, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Please help, I do not do that?

**Comment by Darex1991** [comment]
@findinshop I have the same problem ;/ Do you know how to fix it?

**Comment by yakky** [comment]
@Darex1991 djangocms_blog is only meant to be used through the apphook

**Comment by Darex1991** [comment]
@yakky I fixed it 👍 
```
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
    url(r'^blog/', include('djangocms_blog.urls', namespace='djangocms_blog'))
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

urlpatterns += patterns('', (r'^taggit_suggest/', include('taggit_autosuggest.urls')), )
```
But I have another question:
[#270](https://github.com/nephila/djangocms-blog/issues/270)

**Pull request closed without merging**
