### PR TITLE
Copy placeholders

### PR DESCRIPTION
**Pull request by igerko**

### CODE REVIEW

**Comment by yakky** [comment]
@igerko can you elaborate the goal of this pull request?

**Comment by igerko** [comment]
@yakky that will copy languages of plugins in current translation, eg. when you have translation only for EN and you want to copy to DE you just click copy all plugins from EN.

**Comment by yakky** [comment]
@igerko isn't this already provided by django CMS?

**Comment by igerko** [comment]
yes, but it's not copying post placeholders

**Comment by yakky** [comment]
Closed due to inactivity

**Pull request closed without merging**
