### PR TITLE
CMS Attach menu and language switcher related fixes

### PR DESCRIPTION
**Pull request by skirsdeda**
So this is the text book example of CMSAttachMenu :)
The thing that is not so clear to me is what to do when you are switching language and current object (category or post) doesn't have a translated slug in that language. For Categories I added additional **category_id** url. Not sure what to do with Post.get_absolute_url...

### CODE REVIEW

**Comment by yakky** [comment]
Assigned to myself for review

**Comment by skirsdeda** [comment]
One more thing: how about adding order (integer) field to BlogCategory model. Ordering by category name is no good for me.

**Comment by jedie** [comment]
> One more thing: how about adding order (integer) field to BlogCategory model. Ordering by category name is no good for me.

Yes order by name is not good here, too.

Maybe a optional ordering by usage?!? -> after save a new blog entry: Set oder-integer by usage.

IMHO a new issue for this, would be good.

**Comment by yakky** [comment]
Actually I plan to move to aldryn-categories: current category sytem is very basic and the blog will greatly benefit from using a dedicated categories application, this won't happen in the next month

**Comment by yakky** [comment]
Anyway I don't like the view-by-id solution. Menu shouldn't really care about translations in other languages than the current one.
By using ``active_translations`` manager method you can get the categories that only exist in current language and build the menu on those

**Comment by skirsdeda** [comment]
Should be good now. Build failures seem to be unrelated.

**Comment by yakky** [comment]
@skirsdeda Fixed build errors elsehwere.
Waiting for this to finish for reviewing / Merging

**Comment by yakky** [comment]
@skirsdeda could you add tests to cover the menu and modifier generated nodes?

**Comment by skirsdeda** [comment]
@yakky Allright, I'll see what I can do.

**Comment by yakky** [comment]
@skirsdeda awesome

**Comment by skirsdeda** [comment]
@yakky Tests are in.

**Comment by yakky** [comment]
@skirsdeda this is really great! Thanks for your effort

**Pull request merged**
