### PR TITLE
Added admin filters to support multisite and publishing

### PR DESCRIPTION
**Pull request by leesolway**
#290 

Included a custom admin filter to support multisite permissions.

### CODE REVIEW

**Comment by yakky** [comment]
This looks good. Would you like to add a test for this? Something like this test https://github.com/nephila/djangocms-blog/blob/develop/tests/test_models.py#L200 to check whether the filter is applied correctly

**Comment by yakky** [comment]
@leesolway do you need help to complete this?

**Comment by leesolway** [comment]
Sorry, not had a chance. I can try this weekend to find time, if it fits with your release schedule.

**Comment by yakky** [comment]
No worries, take your time. Just to know if you were stuck needing for help. I'll release a beta without this, while hopefully it will fit the final release

**Comment by leesolway** [comment]
@yakky Sorry won't have a chance to look at this for another week or two. Feel free if you want to drop the test in etc, otherwise i'll look at it then.

**Comment by yakky** [comment]
No worries. Very busy myself too!

**Comment by yakky** [comment]
Thanks @leesolway merging with tests (and a fix) with #332

**Pull request closed without merging**
