### PR TITLE
Make Post.abstract optional

### PR DESCRIPTION
**Pull request by skirsdeda**
Not sure if this is universally useful but I am using blog listings without abstracts (only titles and images)...

### CODE REVIEW

**Comment by yakky** [comment]
@skirsdeda South migration is missing from this PR , do you mind to add it?

**Comment by skirsdeda** [comment]
@yakky Sure, I'll do it.

**Comment by skirsdeda** [comment]
This one should be done.

**Comment by yakky** [comment]
@skirsdeda awesome! thanks

**Pull request merged**
