### PR TITLE
Fix on edit blog post

### PR DESCRIPTION
**Pull request by rafaelgontijo**
In some cases having a situation of a return none, this solves.

### CODE REVIEW

**Comment by yakky** [comment]
@rafaelgontijo actually that should never happen. I would definitely like a test for this

**Comment by sidneijp** [comment]
This the error raised when trying to edit a post:

```
django] ERROR 2018-04-05 14:17:12,849 base 19745 139907703527168 Internal Server Error: /admin/djangocms_blog/post/<id>/change/
Traceback (most recent call last):
  File "<venv>/lib/python3.6/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "<venv>/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "<venv>/lib/python3.6/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "<venv>/lib/python3.6/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "<venv>/lib/python3.6/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "<venv>/lib/python3.6/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "<venv>/lib/python3.6/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "<venv>/lib/python3.6/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "<venv>/lib/python3.6/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 83, in super
    return mark_safe(self.render(self.context))
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "<venv>/lib/python3.6/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 1049, in render
    return render_value_in_context(output, context)
  File "<venv>/lib/python3.6/site-packages/django/template/base.py", line 1026, in render_value_in_context
    value = force_text(value)
  File "<venv>/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "<venv>/lib/python3.6/site-packages/django/utils/html.py", line 390, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "<venv>/lib/python3.6/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "<venv>/lib/python3.6/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "<venv>/lib/python3.6/site-packages/django/contrib/admin/widgets.py", line 291, in render
    'widget': self.widget.render(name, value, *args, **kwargs),
  File "<venv>/lib/python3.6/site-packages/sortedm2m/forms.py", line 52, in render
    for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
  File "<venv>/lib/python3.6/site-packages/django/forms/models.py", line 1110, in __iter__
    yield self.choice(obj)
  File "<venv>/lib/python3.6/site-packages/django/forms/models.py", line 1117, in choice
    return (self.field.prepare_value(obj), self.field.label_from_instance(obj))
  File "<venv>/lib/python3.6/site-packages/django/forms/models.py", line 1180, in label_from_instance
    return smart_text(obj)
  File "<venv>/lib/python3.6/site-packages/django/utils/encoding.py", line 42, in smart_text
    return force_text(s, encoding, strings_only, errors)
  File "<venv>/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
TypeError: __str__ returned non-string (type NoneType)
```

image

image

**Comment by sidneijp** [comment]
The `djangocms-blog` version was `0.9.2`

**Comment by yakky** [comment]
Thanks for sharing. I'll have a look if this hides a more serious issue. If not I'll happily merge this PR

**Comment by sidneijp** [comment]
I've dug a little more. Looks like it's a specific problem that raises when a post has no translations at all. Since it the translation part is parler's responsibility, the way it's done allows this kind of scenery.

So, even with the correction, the final application would still has data problem and this solution would suppress the real problem.

The parler's documentation recommend some ways to deal with missing translation. The use of `safe_translation_getter` is one of them and it depends on the use of the `default` parameter passed to it - if not passed it's `None`.

Translation fallback:
https://django-parler.readthedocs.io/en/latest/advanced/fallback.html

`safe_translation_getter`:
https://github.com/django-parler/django-parler/blob/6324e5f9468dddf7d23d727d12e9870294775742/parler/models.py#L745

I see a design decision here that can lead to different solutions. In my opinion some of the solutions are:

- the @rafaelgontijo suggestion (or the user of `default` parameter in the same way)
- keep raising an error but a more informative one (e.g. there is no translation related to <...>)
- make it easy to program a custom fall back for that (the `default` parameter can be a callable by the way)

**Comment by yakky** [comment]
@rafaelgontijo @sidneijp My preferred solution would be a static `default`. We already have tons of callable / hooks into this blog post model :sweat:

**Comment by yakky** [comment]
Thansk @rafaelgontijo @sidneijp  for your efforts in tackling this!

**Pull request closed without merging**
