### PR TITLE
Fix category menu translation

### PR DESCRIPTION
**Pull request by antwertinger**
The translations for the names in the category menu where not applies when switching between languages. 

The pull request also adds a missing german translation for the subtitle.

### CODE REVIEW

**Comment by yakky** [comment]
@antwertinger thanks for your PR. 
We handle translations in transifex https://www.transifex.com/nephila/djangocms-blog/language/de/
We can't merge po changes from github otherwise the two platform are out of sync and transifex translations will overwrite the github ones when we sync the two
Could you port the additional translations there?

**Comment by fsbraun** [comment]
@antwertinger @yakky I just added the missing the translations to the German language on transifex. It should automatically be pulled when updating translations.

**Comment by yakky** [comment]
@fsbraun :bowing_man: 
@antwertinger could remove po/mo changes to merge the queryset fix?

**Comment by antwertinger** [comment]
Opened a new pull request for the query fix #535

**Comment by yakky** [comment]
@antwertinger great, thanks for the time addressing my comment!

**Pull request closed without merging**
