### PR TITLE
increased slug field length (default is 50)

### PR DESCRIPTION
**Pull request by petrklus**
Increased slug field length for post and category, as discussed in https://github.com/nephila/djangocms-blog/issues/242

### CODE REVIEW

**Comment by yakky** [comment]
@petrklus thanks!
This PR needs south and django migrations to be complete, then it's ready for merge

**Comment by yakky** [comment]
@petrklus also: minor changes are needed in the tests here: https://github.com/nephila/djangocms-blog/blob/develop/tests/test_models.py#L63 and https://github.com/nephila/djangocms-blog/blob/develop/tests/test_models.py#L68 as the full slug field is used to test correct admin rendering

**Comment by petrklus** [comment]
@yakky ok, will amend!

**Comment by yakky** [comment]
@petrklus  great, thanks

**Comment by petrklus** [comment]
@yakky any hints how can I generate south migrations? I am on Django 1.8

**Comment by yakky** [comment]
@petrklus you can:
* deactivate current virtualenv
* cd to the djangocms-blog root directory
* run django 1.6 tests (``tox -epy27-django16-cms31``, for example)
* activate the generated environment ``.tox/py27-django16-cms31/bin/activate``
* create migrazions using djangocms-helper: ``./cms_helper.py makemigrations``

**Comment by petrklus** [comment]
@yakky that did not seem to do the trick for me - so I've created new env with django 1.6, this is where I've gotten now:

    (djangocms_blog_1.6)CUNE-2:tutorial-project petr$ ./manage.py schemamigration djangocms_blog --auto
     ~ Changed field main_image_full on djangocms_blog.Post
     ~ Changed field main_image_thumbnail on djangocms_blog.Post
     ~ Changed field slug on djangocms_blog.BlogCategoryTranslation
     ~ Changed field slug on djangocms_blog.PostTranslation
    Created 0018_auto__chg_field_post_main_image_full__chg_field_post_main_image_thumbn.py. You can now apply this migration with: ./manage.py migrate djangocms_blog

Does the above look alright? Is anything in my config causing the main_image_full and main_image_thumbnail or is it correct?

**Comment by yakky** [comment]
@petrklus you can manually remove the linesregarding main_image_thumbnail_id and main_image_full_id (see https://gist.github.com/yakky/e83dc4ffaccd275b297598211171223f for the exact lines to remove) which are due to unrelated change

**Comment by petrklus** [comment]
@yakky and what about this part:

        u'djangocms_blog.post': {
            'Meta': {'ordering': "(u'-date_published', u'-date_created')", 'object_name': 'Post'},
            'app_config': ('aldryn_apphooks_config.fields.AppHookConfigField', [], {'to': u"orm['djangocms_blog.BlogConfig']", 'null': 'True'}),
            'author': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "u'djangocms_blog_post_author'", 'null': 'True', 'to': u"orm['auth.User']"}),
            'categories': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'blog_posts'", 'blank': 'True', 'to': u"orm['djangocms_blog.BlogCategory']"}),
            'content': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "u'post_content'", 'null': 'True', 'to': "orm['cms.Placeholder']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'date_published': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_published_end': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'enable_comments': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_image': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "u'djangocms_blog_post_image'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': "orm['filer.Image']"}),
            'main_image_full': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "u'djangocms_blog_post_full'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['filer.ThumbnailOption']"}),
            'main_image_thumbnail': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "u'djangocms_blog_post_thumbnail'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['filer.ThumbnailOption']"}),
            'publish': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'sites': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['sites.Site']", 'symmetrical': 'False', 'blank': 'True'})
        },

Wouldn't there be a discrepancy?

**Comment by petrklus** [comment]
@yakky I have now removed any difference other than the slug

**Comment by yakky** [comment]
@petrklus awesome job! Waiting for tests to finish before merging
Thanks for contributing this and your patience in taking care of the details

**Comment by petrklus** [comment]
@yakky my pleasure! by the way, are there any breaking changes when upgrading from 0.6.3 to 0.8?

**Comment by yakky** [comment]
@petrklus no breaking. Just fixes and new features added; the only big change in terms of compatibility is support for new django-meta, so you may want to drop django-meta-mixin from your environment

**Comment by yakky** [comment]
@petrklus merged. thanks for contributing this!

**Pull request merged**
