### PR TITLE
Add media placeholder with custom base plugin for media plugins

### PR DESCRIPTION
**Pull request by yakky**
This is  an alternative approach to #473 

It relies on plugins and includes into the core as little knowledge as possible:

- ``MediaAttachmentPluginMixin`` is not much more than an interface, with some utility methods. The only public API are ``MediaAttachmentPluginMixin.get_main_image`` and ``MediaAttachmentPluginMixin.get_thumb_image`` the rest being just a convenient abstraction that concrete plugins might use, but are not forced to. This allows for example to use existing plugins just by extending them.
- ``media`` is  a dedicated placeholder to handle differently its plugins
- ``media_images`` is the templatetag that extracts the images from the plugins. unfortunately we cannot handle this inside the model as we need the ``request`` object to get the concrete plugins list

- ``YouTubePlugin`` and ``VimeoPlugin`` are just an example of possible plugin implementation, based on code from #473 

This approach puts the responsibility of getting the media content outside the djangocms-blog code, and allows for much greater customization than anything inside djangocms-blog could provide

@fsbraun what do you think?

Closes #473

### CODE REVIEW

**Comment by fsbraun** [comment]
Hi @yakki!

This looks like a very Django-CMS-ish ways of doing it. Very nice! Let me think about and play with this. 

What comes to my mind immediately:

- Maybe an **additional template tag** can render the media object itself (e.g., if I click on a media thumbnail in a blog post list a pop-over player appears), or a post detail view renders the player in stead of the main image still.
- Placeholder configuration could restrict the number of media plugins if necessary
- How could the media plugins be accessed in the main post placeholder? (Context + another plugin type?)

Anyway, let me come back to you with my thoughts after a little playing around!

**Comment by yakky** [comment]
It might be complicated to get the plugins from `media` placeholder in `content`; we might drop the `media` placeholder use a custom templatetag to only render the plugins which implement a specific interface or subclass a specific class, to let user add media plugins in the main placeholder a extract what we need in the "special" one

**Comment by fsbraun** [comment]
Just a thought:

What if we skip the the ``media`` placeholder and in stead scan the ``post_content`` placeholder for plugins with the specific interface? This implies that media previews only appear from plugins actually shown in the content.

Downside: The missing additional ``media``  placeholder that leads to users asking "What's that for?" We would need to give concrete examples on how to build plugins with the mixins in the documentation.

**Comment by yakky** [comment]
I think that the only design decision we need is whether we might want to support the use case of having multimedia content and text content rendered in different places in the post detail template; that will require two placeholders as overriding ``render_placeholder`` will require significant effort and code duplication which would be hard to maintain.

The rich preview mode can be easily achieved by allowing ``MediaAttachmentPluginMixin`` to render a template instead of just returning an image path for preview

**Comment by yakky** [comment]
@fsbraun any further thoughts on this? I will have some time this summer to work on OSS projects and I would like to finalize this

**Comment by fsbraun** [comment]
@yakki Thanks for following up! I am inclined to follow the route you suggest. However, I would also suggest to extend the template tags. Sorry, I am not git-savvy and do not know how to suggest this specific change to this pull request. However, this would be my ``djangocms_blog.py`` in ``templatetags``:

    # -*- coding: utf-8 -*-
    from __future__ import absolute_import, print_function, unicode_literals

    from cms.utils.plugins import get_plugins
    from django import template

    register = template.Library()


    @register.simple_tag(name='media_content', takes_context=True)
    def media_content(context, post):
        request = context['request']
        if post.media.get_plugins().exists():
            plugins = get_plugins(request, post.media, None)
            return plugins
        return []

    @register.simple_tag(name='media_thumbnails', takes_context=True)
    def media_thumbnails(context, post):
        return [
                plugin.get_thumb_image() for plugin in media_content(context, post)
                    if hasattr(plugin, 'get_thumb_image')
        ]

    @register.simple_tag(name='media_images', takes_context=True)
    def media_images(context, post):
        return [
                plugin.get_main_image() for plugin in media_content(context, post)
                    if hasattr(plugin, 'get_main_image')
        ]

It should allow for rich media post lists, rendering of post media in the post itself and also be sufficiently clear to the user.

**Comment by fsbraun** [comment]
... and also it feels very django-cms-like!

**Comment by yakky** [comment]
@fsbraun thanks for the input
How about this slightly refactored version of your proposal?

**Comment by fsbraun** [comment]
Looks good, however, does it make sense to also allow to get the plugins themselves? I am thinking  of a situation where you have more than one plugin and thumbnails and images as well as the plugin itself need to aligned. (Say, the first plugin does not provide a thumbnail for whatever reason  – this could throw images and thumbnails out of sync.)

**Comment by yakky** [comment]
@fsbraun could you explain the use case in more detail?

If you need to render a plugin and its image side by side, wouldn't be easier just to handle this inside the plugin? We can easily return an "hole" in the images returned by `media_images`, but it feels a bit weird

**Comment by fsbraun** [comment]
@yakky Not sure I fully thought this through.  Holes in lists imho do not make a lot of sense. The placeholder can be rendered both in post lists and in post details. 

I had a situation in mind where, say, you have a slider with a set of video thumbnails and upon click you would show the corresponding video (i.e. video plugin). However, it might have escaped my thoughts that there probably is a template tag missing that renders a single plugin (call ``render`` method and then ``render_to_string``  with the plugin's ``render_template`` property as template?).

Implementation would probably also require ajax calls to get the plugin after the click and to this end a plugin id to identify the clicked video plugin and a way to render a plugin with that id.

I am not saying this should be provided out of the box, only that it should be possible. I rendered that this would be the case if a template tag returns the list of plugins (from which you can get thumbnails, images, ids, and - as in my case - you could check for ajax functionality).

Is there a reason not to provide the plugin list to the template?

**Comment by yakky** [comment]
this templatetag returns the list of plugins in the `media` placeholder https://github.com/nephila/djangocms-blog/pull/490/files#diff-8f27c57c555413ebf2b1e46ac3c10868R32
You can then render as a whole or one by one as documented in the docstring

**Comment by fsbraun** [comment]
@yakky Sorry, I completely did not see this! Those capable of reading are in clear advantage ;-)  This is perfect for me!!

**Comment by yakky** [comment]
:+1: thanks for your review. I will try to finalize this in the next few days

**Comment by yakky** [comment]
@fsbraun it took me a while more, but this should be complete.

I also added documentation and tests

**Comment by yakky** [comment]
@whyronimus this PR is feature complete but not merged. I'd be glad if you could test / review / comment the current implementation

**Comment by whyronimus** [comment]
I got it implemented, and it looks really nice. Excellent work!

The only potential drawback is the necessity to write specific plugins with the JSON request: not all users will take the effort to dig into the the APIs of services like youtube, but of course it's difficult to maintain if the platforms are changing their APIs etc.

The basic functionality of replacing the main image of the post with a video also works with the djangocms-video plugin which has the option to set a "poster" image. (e.g. still frame of the video) But: In the post list, the preview images are not working when using this. Would it be possible to access this still image of the child plugin?

**Comment by yakky** [comment]
@whyronimus by using `get_media_plugins` templatetag (https://github.com/nephila/djangocms-blog/pull/490/files#diff-8f27c57c555413ebf2b1e46ac3c10868R11) you can get all the plugins in the `media` placeholder and pick the proper field.

I could add some documentation to use `djangocms-video` as it's doable with the current implementation by just doing some checks in the template

Actually it may worth to just implement support for the `poster` attribute of `djangocms-video` in `media_images`, it's just another `if`

**Comment by yakky** [comment]
@whyronimus 😳 I do love single malt, but I haven't done much 🙇
@fsbraun what do you think if I merge this and release as 1.0?

**Comment by fsbraun** [comment]
@yakky I'd appreciate it very much if this could be including 1.0!! ... and YOU did the work!!

**Comment by yakky** [comment]
Let's pull the trigger :)

**Pull request merged**
