### PR TITLE
Feature/category feed

### PR DESCRIPTION
**Pull request by palmitoto**
Hello,
this is a merge request to add a rss category feed.
In addition to the default settings, the number of items to display can be passed by parameters.

### CODE REVIEW

**Comment by yakky** [comment]
@palmitoto thanks for your contribution
any reason for the quote style changes?
It makes quite difficult to read your PR and it does not conform to repository style guide

**Comment by palmitoto** [comment]
Ok, i will drop this PR and make another one without quote style changes...

**Comment by yakky** [comment]
@palmitoto just e heads up: we are going to release 1.1 this coming week, if you are interested in getting this merged, and you want in 1.1 I ask you to open the new PR in a couple of days.

**Comment by palmitoto** [comment]
Oh yeah, i try to do this today :-)

**Comment by palmitoto** [comment]
Replaced by MR #544

**Pull request closed without merging**
