### PR TITLE
Bugfix/#565 individual test cases

### PR DESCRIPTION
**Pull request by g3rb3n**
Fixes the problem I encountered while following the documentation.

https://github.com/nephila/djangocms-blog/issues/565

### CODE REVIEW

**Comment by yakky** [comment]
@g3rb3n thanks for your contribution

The contribution guide makes some hidden assumption on the workflow, I will happily merge your contribution.

Be aware that we are in the process of completely  revamping the tooling (and partially the codestyle) and we rewrote most of the contribution guide, have a look here for a sneak peek https://github.com/nephila/djangocms-blog/blob/feature/issue-564-update-tooling/CONTRIBUTING.rst

**Comment by g3rb3n** [comment]
@yakky I just setup the dev env for blog and encountered more things. Maybe this is a good opportunity to update these docs. But maybe it is a better idea to follow the new workflow. What do you think?

**Comment by yakky** [comment]
I think it's a good opportunity to check if the new workflow provides a more solid environment for an external contributor :)

check branch `feature/issue-564-update-tooling` and its updated contributing guide https://github.com/nephila/djangocms-blog/blob/93718c0d922d3a414b97c68ec30203f892d7f002/CONTRIBUTING.rst

**Comment by g3rb3n** [comment]
I have read the new docs, looks better! But you also mentioned that this is completely revamping the tooling.

Can I work on develop with this new documentation? Or do I need to branch out of the 564 branch?

**Comment by yakky** [comment]
thanks for the review!

It's better if you branch off the 564, I plan to merge #564 tomorrow, so this won't slow your PR, you can open the PR against the branch in 564, and I will rebase after 564 has been merged

**Comment by g3rb3n** [comment]
Nice! That will do.

**Pull request merged**
